import Head from "next/head";
import { useSession, signOut } from "next-auth/react";
import { Button } from "@mui/material";

export default function Home() {
  const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          {session && (
            <>
              Signed in as {session?.user?.email} <br />
              <Button
                size="small"
                variant="contained"
                className="bg-amber-600"
                onClick={() => signOut({ callbackUrl: "/signin" })}
              >
                Sign out
              </Button>
            </>
          )}
        </div>
      </main>
    </div>
  );
}
